# ============================================================
# NOVEL CHAPTER JSON -> IMAGE GENERATOR
# MeinaMix V11 / SD 1.5 / NVIDIA RTX 2050 4GB
#
# INPUT:
#   chapter JSON generated by the master prompt
#
# OUTPUT:
#   outputs/<chapter_id>/
#       PANEL_01.png
#       PANEL_02.png
#       ...
#       prompts_log.json
#
# IMPORTANT:
#   The JSON is the source of truth.
#   One PANEL = one generated image.
#   TTS chunks are NOT used to create extra images.
# ============================================================

import os
import re
import json
import argparse
from pathlib import Path

import torch
from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler


# ============================================================
# CONFIG
# ============================================================

BASE_DIR = Path(__file__).resolve().parent

MODEL_PATH = BASE_DIR / "models" / "meinamix_meinaV11.safetensors"
DEFAULT_JSON = BASE_DIR / "chapter.json"
OUTPUT_ROOT = BASE_DIR / "outputs"

# RTX 2050 4GB: keep this conservative.
WIDTH, HEIGHT = 768, 432

STEPS = 150 
CFG = 7.0
CLIP_SKIP = None

BASE_SEED = 5000
NUM_VARIANTS = 1
RESUME = True

# Keep the common negative prompt short because SD1.5 has a small
# text-conditioning budget.
NEGATIVE = (
    "worst quality, low quality, lowres, blurry, jpeg artifacts, "
    "bad anatomy, bad hands, extra fingers, missing fingers, extra arms, "
    "extra legs, fused fingers, deformed face, duplicate, multiple views, "
    "cropped, out of frame, text, watermark, signature, 3d, chibi, "
    "modern clothes, photorealistic , "
)

QUALITY = (
    "masterpiece, best quality, anime screencap, cinematic anime, "
    "detailed illustration, dramatic lighting"
)


# ============================================================
# HELPERS
# ============================================================

def clean_text(value):
    """Normalize text coming from JSON."""
    if value is None:
        return ""
    return str(value).strip()


def safe_name(value):
    """Make a Windows-safe filename."""
    value = clean_text(value)
    value = re.sub(r'[<>:"/\\|?*]', "_", value)
    value = re.sub(r"\s+", "_", value)
    return value[:100] or "chapter"


def load_json(path):
    """
    Load the chapter JSON.

    Supported formats:

    1) Current chapter JSON format:
       {
           "project": "...",
           "chapter": "अध्याय 1 — ...",
           "format": "16:9",
           "language": "Hindi",
           "style": "...",
           "continuity_rules": [...],
           "scenes": [...]
       }

    2) Legacy wrapped format:
       {
           "chapter": {
               "chapter_id": "...",
               "chapter_title": "...",
               "scenes": [...]
           }
       }

    The current JSON is the source of truth and is NOT modified on disk.
    """

    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, dict):
        raise ValueError("JSON root object/dict hona chahiye.")

    # ------------------------------------------------------------
    # CURRENT FORMAT
    # The uploaded chapter JSON has "chapter" as a STRING and
    # "scenes" directly at the root.
    # ------------------------------------------------------------
    if isinstance(data.get("chapter"), str) and "scenes" in data:
        chapter_title = clean_text(data.get("chapter"))

        chapter = {
            "chapter_id": safe_name(chapter_title) or "CHAPTER",
            "chapter_title": chapter_title,
            "format": data.get("format", "16:9"),
            "language": data.get("language", "Hindi"),
            "style": data.get("style", ""),
            "continuity_rules": data.get("continuity_rules", []),
            "memory": data.get("memory", {}),
            "scenes": data.get("scenes", []),
        }

        if not isinstance(chapter["scenes"], list):
            raise ValueError("Root 'scenes' list hona chahiye.")

        return chapter

    # ------------------------------------------------------------
    # LEGACY FORMAT
    # ------------------------------------------------------------
    if "chapter" not in data:
        raise ValueError(
            "JSON format invalid: root me 'chapter' nahi mila."
        )

    chapter = data["chapter"]

    if not isinstance(chapter, dict):
        raise ValueError(
            "'chapter' string hai aur root 'scenes' nahi mile. "
            "Current chapter JSON format check karo."
        )

    if "scenes" not in chapter:
        raise ValueError("'chapter.scenes' nahi mila.")

    if not isinstance(chapter["scenes"], list):
        raise ValueError("'chapter.scenes' list hona chahiye.")

    return chapter


def flatten_panels(chapter):
    """Return panels in exact story order."""
    panels = []

    for scene_index, scene in enumerate(chapter.get("scenes", []), 1):
        scene_id = scene.get("scene_id", f"SCENE_{scene_index:02d}")
        scene_title = scene.get("scene_title", scene.get("title", ""))
        scene_type = scene.get("scene_type", "PRESENT")

        for panel_index, panel in enumerate(scene.get("panels", []), 1):
            if not isinstance(panel, dict):
                continue

            panel_copy = dict(panel)
            panel_copy["_scene_id"] = scene_id
            panel_copy["_scene_title"] = scene_title
            panel_copy["_scene_type"] = panel.get("scene_type", scene_type)
            panel_copy["_scene_index"] = scene_index
            panel_copy["_panel_index_in_scene"] = panel_index

            panels.append(panel_copy)

    return panels


# ============================================================
# MEMORY -> VISUAL CHARACTER / OBJECT TAGS
# ============================================================

def build_memory_visuals(memory):
    """
    Convert the chapter memory into compact visual tags.

    This is important because MeinaMix/SD1.5 understands visual tags
    much better than canonical Hindi entity names.

    Example:
        युन चे
    becomes:
        young man, black hair, black eyes, black robe, blood-stained
        clothes, deep wounds
    """

    visual_map = {}

    # Characters
    for entity_id, data in memory.get("characters", {}).items():
        if not isinstance(data, dict):
            continue

        name = clean_text(data.get("name"))
        appearance = clean_text(data.get("appearance"))

        if not name:
            continue

        tags = appearance

        # Add a few useful visual anchors from the memory.
        # Do not invent appearance if memory doesn't contain it.
        if tags:
            visual_map[name] = tags

    # Locations
    for entity_id, data in memory.get("locations", {}).items():
        if not isinstance(data, dict):
            continue

        name = clean_text(data.get("name"))
        description = clean_text(data.get("description"))

        if name and description:
            visual_map[name] = description

    # Objects
    for entity_id, data in memory.get("objects", {}).items():
        if not isinstance(data, dict):
            continue

        name = clean_text(data.get("name"))
        description = clean_text(data.get("description"))

        if name and description:
            visual_map[name] = description

    return visual_map


def visualize_canonical_names(prompt, visual_map):
    """
    Replace canonical Hindi entity names in image prompts with their
    visual memory descriptions.

    This keeps the production JSON canonical while making the actual
    SD prompt model-friendly.
    """

    result = clean_text(prompt)

    # Longest first prevents partial replacement problems.
    names = sorted(visual_map.keys(), key=len, reverse=True)

    for name in names:
        description = visual_map[name]

        if not name or not description:
            continue

        # Replace exact canonical name.
        result = result.replace(name, description)

    return result


# ============================================================
# VOICE -> OPTIONAL VISUAL HINT
# ============================================================

def panel_voice_text(panel):
    voice = panel.get("voice", [])

    if not isinstance(voice, list):
        return ""

    parts = []

    for item in voice:
        if not isinstance(item, dict):
            continue

        text = clean_text(item.get("text"))
        if text:
            parts.append(text)

    return " ".join(parts)


# ============================================================
# PROMPT CLEANING
# ============================================================

def comma_tags(text):
    """
    Convert the prompt into comma-separated visual phrases.

    Existing image_prompt can be a natural sentence. We preserve it
    instead of aggressively rewriting the user's generated prompt.
    """

    text = clean_text(text)
    text = re.sub(r"\s+", " ", text)
    return text


def token_count(tokenizer, text):
    return len(tokenizer(text).input_ids) - 2


def fit_prompt(tokenizer, text, limit=75):
    """
    SD1.5 CLIP has a small text-conditioning limit.

    Remove low-priority comma-separated phrases from the END.
    """

    text = comma_tags(text)

    if token_count(tokenizer, text) <= limit:
        return text, []

    parts = [x.strip() for x in text.split(",") if x.strip()]
    dropped = [] 

    while len(parts) > 1 and token_count(tokenizer, ", ".join(parts)) > limit:
        dropped.append(parts.pop())
 
    return ", ".join(parts), dropped


def build_prompt(pipe, panel, visual_map):
    raw = clean_text(panel.get("image_prompt"))

    if not raw:
        raise ValueError(
            f"{panel.get('panel_id', 'UNKNOWN')} me image_prompt missing hai."
        )

    # Canonical Hindi names are converted to visual descriptions ONLY
    # for the actual image-generation prompt.
    visual_prompt = visualize_canonical_names(raw, visual_map)

    scene_type = clean_text(panel.get("_scene_type", "PRESENT"))

    style = QUALITY

    if scene_type == "FLASHBACK":
        style += ", soft memory atmosphere, cinematic flashback"

    prompt = f"{style}, {visual_prompt}"

    final_prompt, dropped = fit_prompt(pipe.tokenizer, prompt)

    return final_prompt, dropped


def build_negative(pipe):
    final_negative, dropped = fit_prompt(pipe.tokenizer, NEGATIVE)
    if dropped:
        print("Warning: negative prompt trimmed:", dropped)
    return final_negative


# ============================================================
# MODEL
# ============================================================

def load_pipeline():
    if not MODEL_PATH.is_file():
        raise FileNotFoundError(
            f"MeinaMix model nahi mila:\n{MODEL_PATH}\n\n"
            "Model ko models/meinamix_meinaV11.safetensors me rakho."
        )

    if not torch.cuda.is_available():
        raise RuntimeError(
            "CUDA available nahi hai. NVIDIA driver + CUDA PyTorch check karo."
        )

    print("=" * 70)
    print("NOVEL CHAPTER -> IMAGE GENERATOR")
    print("=" * 70)
    print("GPU:", torch.cuda.get_device_name(0))
    print(
        f"VRAM: "
        f"{torch.cuda.get_device_properties(0).total_memory / 1024**3:.2f} GB"
    )
    print("Model:", MODEL_PATH)

    pipe = StableDiffusionPipeline.from_single_file(
        str(MODEL_PATH),
        torch_dtype=torch.float16,
        use_safetensors=True,
        safety_checker=None,
    )

    pipe.scheduler = DPMSolverMultistepScheduler.from_config(
        pipe.scheduler.config,
        use_karras_sigmas=True,
    )

    # Important for RTX 2050 4GB.
    pipe.enable_model_cpu_offload()

    for fn in (
        "enable_attention_slicing",
        "enable_vae_slicing",
        "enable_vae_tiling",
    ):
        try:
            getattr(pipe, fn)()
        except Exception:
            pass

    print("MeinaMix loaded.")
    return pipe


# ============================================================
# GENERATION
# ============================================================

def generate(chapter_json):
    chapter = load_json(chapter_json)

    chapter_id = clean_text(chapter.get("chapter_id", "CHAPTER"))
    chapter_title = clean_text(chapter.get("chapter_title", ""))

    output_dir = OUTPUT_ROOT / safe_name(chapter_id)
    output_dir.mkdir(parents=True, exist_ok=True)

    memory = chapter.get("memory", {})
    visual_map = build_memory_visuals(memory)

    panels = flatten_panels(chapter)

    if not panels:
        raise ValueError("Chapter me koi panel nahi mila.")

    pipe = load_pipeline()
    neg_final = build_negative(pipe)

    print()
    print("Chapter:", chapter_title)
    print("Chapter ID:", chapter_id)
    print("Panels:", len(panels))
    print("Size:", f"{WIDTH}x{HEIGHT}")
    print("Steps:", STEPS)
    print("CFG:", CFG)
    print("Output:", output_dir)
    print()

    log = []

    for order, panel in enumerate(panels, 1):
        panel_id = clean_text(panel.get("panel_id")) or f"PANEL_{order:03d}"

        title = clean_text(panel.get("_scene_title"))
        scene_id = clean_text(panel.get("_scene_id"))
        scene_type = clean_text(panel.get("_scene_type", "PRESENT"))

        prompt, dropped = build_prompt(pipe, panel, visual_map)

        voice_text = panel_voice_text(panel)

        panel_log = {
            "order": order,
            "panel_id": panel_id,
            "scene_id": scene_id,
            "scene_title": title,
            "scene_type": scene_type,
            "prompt": prompt,
            "dropped_prompt_tags": dropped,
            "voice_text": voice_text,
        }

        log.append(panel_log)

        for variant in range(NUM_VARIANTS):
            suffix = "" if NUM_VARIANTS == 1 else f"_v{variant + 1}"

            filename = f"{order:03d}_{safe_name(panel_id)}{suffix}.png"
            path = output_dir / filename

            if RESUME and path.is_file():
                print(
                    f"[{order:02d}/{len(panels)}] SKIP "
                    f"{panel_id} -> already exists"
                )
                continue

            # Deterministic seed:
            # same panel + same settings = reproducible result.
            seed = BASE_SEED + order * 100 + variant

            print(
                f"[{order:02d}/{len(panels)}] "
                f"{panel_id} | {scene_type} | seed {seed}"
            )

            print("   scene:", title)

            if dropped:
                print("   trimmed:", ", ".join(dropped))

            generator = torch.Generator(device="cuda").manual_seed(seed)

            try:
                torch.cuda.empty_cache()

                with torch.inference_mode():
                    result = pipe(
                        prompt=prompt,
                        negative_prompt=neg_final,
                        width=WIDTH,
                        height=HEIGHT,
                        num_inference_steps=STEPS,
                        guidance_scale=CFG,
                        clip_skip=CLIP_SKIP,
                        generator=generator,
                    )

                image = result.images[0]
                image.save(path)

                print("   saved:", path)

                del image
                del result

            except torch.cuda.OutOfMemoryError:
                torch.cuda.empty_cache()

                print(
                    "\nCUDA OUT OF MEMORY.\n"
                    "Current resolution: 768x432\n"
                    "Try WIDTH, HEIGHT = 640, 360\n"
                    "or reduce STEPS to 20-24.\n"
                )

                raise

            except Exception as exc:
                print(f"   FAILED: {type(exc).__name__}: {exc}")

            finally:
                torch.cuda.empty_cache()

    log_path = output_dir / "prompts_log.json"

    with open(log_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "chapter_id": chapter_id,
                "chapter_title": chapter_title,
                "format": chapter.get("format", "16:9"),
                "total_panels": len(panels),
                "panels": log,
            },
            f,
            ensure_ascii=False,
            indent=2,
        )

    generated = 0
    for order, panel in enumerate(panels, 1):
        panel_id = clean_text(panel.get("panel_id")) or f"PANEL_{order:03d}"
        filename = f"{order:03d}_{safe_name(panel_id)}.png"

        if (output_dir / filename).is_file():
            generated += 1

    print()
    print("=" * 70)
    print("DONE")
    print(f"Generated: {generated}/{len(panels)}")
    print("Output:", output_dir)
    print("Log:", log_path)
    print("=" * 70)


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate one image for every panel in chapter JSON."
    )

    parser.add_argument(
        "json_file",
        nargs="?",
        default=str(DEFAULT_JSON),
        help="Chapter JSON file path.",
    )

    args = parser.parse_args()

    json_path = Path(args.json_file)

    if not json_path.is_file():
        raise FileNotFoundError(
            f"Chapter JSON nahi mila: {json_path}\n\n"
            "Example:\n"
            "python generate_from_chapter.py chapter.json"
        )

    generate(json_path)
 